### ISSUE TITLE
Crash wen trying to add a new repo

### ISSUE THREAD

**Issue by naveenjohnsonv** [redsolver/skydroid#10]
Trying to add a new repository causes app  to crash.

```
time: 1612146652481
msg: java.lang.AbstractMethodError: abstract method "android.view.WindowInsets android.view.WindowInsetsAnimation$Callback.onProgress(android.view.WindowInsets, java.util.List)"
stacktrace: java.lang.AbstractMethodError: abstract method "android.view.WindowInsets android.view.WindowInsetsAnimation$Callback.onProgress(android.view.WindowInsets, java.util.List)"
	at android.view.View.dispatchWindowInsetsAnimationProgress(View.java:11384)
	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7433)
	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7439)
	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7439)
	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7439)
	at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7439)
	at android.view.ViewRootInsetsControllerHost.dispatchWindowInsetsAnimationProgress(ViewRootInsetsControllerHost.java:106)
	at android.view.InsetsController.lambda$new$2$InsetsController(InsetsController.java:575)
	at android.view.-$$Lambda$InsetsController$zpmOxHfTFV_3me2u3C8YaXSUauQ.run(Unknown Source:2)
	at android.view.InsetsController.scheduleApplyChangeInsets(InsetsController.java:1355)
	at android.view.InsetsAnimationControlImpl.setInsetsAndAlpha(InsetsAnimationControlImpl.java:186)
	at android.view.InsetsAnimationControlImpl.setInsetsAndAlpha(InsetsAnimationControlImpl.java:170)
	at android.view.InsetsController$InternalAnimationControlListener.lambda$onReady$0$InsetsController$InternalAnimationControlListener(InsetsController.java:332)
	at android.view.-$$Lambda$InsetsController$InternalAnimationControlListener$SInf91MjJKDQFXwrp7C-HBi0xaQ.onAnimationUpdate(Unknown Source:13)
	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1566)
	at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:692)
	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:655)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1087)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
	at android.view.InsetsController$InternalAnimationControlListener.onReady(InsetsController.java:349)
	at android.view.InsetsController.lambda$startAnimation$6$InsetsController(InsetsController.java:1338)
	at android.view.-$$Lambda$InsetsController$VzAUS17blucBK1u6-37NlEpdYqI.run(Unknown Source:12)
	at android.view.ViewRootInsetsControllerHost$1.onPreDraw(ViewRootInsetsControllerHost.java:67)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3094)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8185)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1027)
	at android.view.Choreographer.doCallbacks(Choreographer.java:851)
	at android.view.Choreographer.doFrame(Choreographer.java:786)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by redsolver** [comment]
Which device and OS version are you using?

**Comment by naveenjohnsonv** [comment]
> Which device and OS version are you using?

Mi 9T Pro, Android 11 (Custom ROM)

**Comment by redsolver** [comment]
Please check if Version 0.3.0 (https://github.com/redsolver/skydroid/releases/tag/v0.3.0) fixes this.

**Comment by naveenjohnsonv** [comment]
@redsolver Yep, looks like it is resolved
